# fmt: off

from typing import TypeVar, overload

from quadrants.types.primitive_types import f32, f64, i16, i32, i64, u16, u32, u64

import quadrants_typing as qdt
from quadrants_typing._algebra import _Col, _Dim, _Num, _Row

pi: float
e: float
inf: float
nan: float

# vector / matrix constructors

vec2 = qdt.Vec[float, qdt.Dim2]
vec3 = qdt.Vec[float, qdt.Dim3]
vec4 = qdt.Vec[float, qdt.Dim4]
ivec2 = qdt.Vec[int, qdt.Dim2]
ivec3 = qdt.Vec[int, qdt.Dim3]
ivec4 = qdt.Vec[int, qdt.Dim4]
uvec2 = qdt.Vec[qdt.uint, qdt.Dim2]
uvec3 = qdt.Vec[qdt.uint, qdt.Dim3]
uvec4 = qdt.Vec[qdt.uint, qdt.Dim4]
mat2 = qdt.Mat[float, qdt.Dim2, qdt.Dim2]
mat3 = qdt.Mat[float, qdt.Dim3, qdt.Dim3]
mat4 = qdt.Mat[float, qdt.Dim4, qdt.Dim4]

# unary element-wise
#
# One overload per shape. `_Num` is a constrained TypeVar over every concrete
# dtype, so a scalar echoes its exact type back and a container echoes its exact
# element and dimensions back — no widening, no builtin/nominal split.

# acos
@overload  # scalar
def acos(x: _Num) -> _Num: ...
@overload  # vector
def acos(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def acos(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# asin
@overload  # scalar
def asin(x: _Num) -> _Num: ...
@overload  # vector
def asin(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def asin(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# cos
@overload  # scalar
def cos(x: _Num) -> _Num: ...
@overload  # vector
def cos(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def cos(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# sin
@overload  # scalar
def sin(x: _Num) -> _Num: ...
@overload  # vector
def sin(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def sin(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# tan
@overload  # scalar
def tan(x: _Num) -> _Num: ...
@overload  # vector
def tan(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def tan(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# tanh
@overload  # scalar
def tanh(x: _Num) -> _Num: ...
@overload  # vector
def tanh(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def tanh(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# exp
@overload  # scalar
def exp(x: _Num) -> _Num: ...
@overload  # vector
def exp(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def exp(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# log
@overload  # scalar
def log(x: _Num) -> _Num: ...
@overload  # vector
def log(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def log(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# log2
@overload  # scalar
def log2(x: _Num) -> _Num: ...
@overload  # vector
def log2(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def log2(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# sqrt
@overload  # scalar
def sqrt(x: _Num) -> _Num: ...
@overload  # vector
def sqrt(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def sqrt(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# fract
@overload  # scalar
def fract(x: _Num) -> _Num: ...
@overload  # vector
def fract(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def fract(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# degrees
@overload  # scalar
def degrees(x: _Num) -> _Num: ...
@overload  # vector
def degrees(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def degrees(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# radians
@overload  # scalar
def radians(x: _Num) -> _Num: ...
@overload  # vector
def radians(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def radians(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# sign
@overload  # scalar
def sign(x: _Num) -> _Num: ...
@overload  # vector
def sign(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def sign(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[_Num, _Row, _Col]: ...

# unary element-wise with dtype

# ceil
@overload  # scalar
def ceil(x: _Num, dtype: type[qdt.Number] | None = None) -> _Num: ...
@overload  # vector
def ceil(x: qdt.Vec[_Num, _Dim], dtype: type[qdt.Number] | None = None) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def ceil(x: qdt.Mat[_Num, _Row, _Col], dtype: type[qdt.Number] | None = None) -> qdt.Mat[_Num, _Row, _Col]: ...

# floor
@overload  # scalar
def floor(x: _Num, dtype: type[qdt.Number] | None = None) -> _Num: ...
@overload  # vector
def floor(x: qdt.Vec[_Num, _Dim], dtype: type[qdt.Number] | None = None) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def floor(x: qdt.Mat[_Num, _Row, _Col], dtype: type[qdt.Number] | None = None) -> qdt.Mat[_Num, _Row, _Col]: ...

# round
@overload  # scalar
def round(x: _Num, dtype: type[qdt.Number] | None = None) -> _Num: ...
@overload  # vector
def round(x: qdt.Vec[_Num, _Dim], dtype: type[qdt.Number] | None = None) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def round(x: qdt.Mat[_Num, _Row, _Col], dtype: type[qdt.Number] | None = None) -> qdt.Mat[_Num, _Row, _Col]: ...

# binary / ternary element-wise
#
# These broadcast a scalar against the container, so the scalar arg shares the
# container's element type via the same `_Num`: `Vec[_Num, _Dim] | _Num`.

# atan2
@overload  # scalar
def atan2(x1: _Num, x2: _Num) -> _Num: ...
@overload  # vector
def atan2(x1: qdt.Vec[_Num, _Dim] | _Num, x2: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def atan2(x1: qdt.Mat[_Num, _Row, _Col] | _Num, x2: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[_Num, _Row, _Col]: ...

# mod
@overload  # scalar
def mod(x: _Num, y: _Num) -> _Num: ...
@overload  # vector
def mod(x: qdt.Vec[_Num, _Dim] | _Num, y: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def mod(x: qdt.Mat[_Num, _Row, _Col] | _Num, y: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[_Num, _Row, _Col]: ...

# pow
@overload  # scalar
def pow(base: _Num, exponent: _Num) -> _Num: ...
@overload  # vector
def pow(base: qdt.Vec[_Num, _Dim] | _Num, exponent: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def pow(base: qdt.Mat[_Num, _Row, _Col] | _Num, exponent: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[_Num, _Row, _Col]: ...

# clamp
@overload  # scalar
def clamp(x: _Num, xmin: _Num, xmax: _Num) -> _Num: ...
@overload  # vector
def clamp(x: qdt.Vec[_Num, _Dim] | _Num, xmin: qdt.Vec[_Num, _Dim] | _Num, xmax: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def clamp(x: qdt.Mat[_Num, _Row, _Col] | _Num, xmin: qdt.Mat[_Num, _Row, _Col] | _Num, xmax: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[_Num, _Row, _Col]: ...

# mix
@overload  # scalar
def mix(x: _Num, y: _Num, a: _Num) -> _Num: ...
@overload  # vector
def mix(x: qdt.Vec[_Num, _Dim] | _Num, y: qdt.Vec[_Num, _Dim] | _Num, a: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def mix(x: qdt.Mat[_Num, _Row, _Col] | _Num, y: qdt.Mat[_Num, _Row, _Col] | _Num, a: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[_Num, _Row, _Col]: ...

# smoothstep
@overload  # scalar
def smoothstep(edge0: _Num, edge1: _Num, x: _Num) -> _Num: ...
@overload  # vector
def smoothstep(edge0: qdt.Vec[_Num, _Dim] | _Num, edge1: qdt.Vec[_Num, _Dim] | _Num, x: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[_Num, _Dim]: ...
@overload  # matrix
def smoothstep(edge0: qdt.Mat[_Num, _Row, _Col] | _Num, edge1: qdt.Mat[_Num, _Row, _Col] | _Num, x: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[_Num, _Row, _Col]: ...

# step (returns f32 elements, so the container type is not preserved)
@overload  # scalar
def step(edge: _Num, x: _Num) -> float: ...
@overload  # vector
def step(edge: qdt.Vec[_Num, _Dim] | _Num, x: qdt.Vec[_Num, _Dim] | _Num) -> qdt.Vec[f32, _Dim]: ...
@overload  # matrix
def step(edge: qdt.Mat[_Num, _Row, _Col] | _Num, x: qdt.Mat[_Num, _Row, _Col] | _Num) -> qdt.Mat[f32, _Row, _Col]: ...

# min / max

_MinMaxCompatibleNum = TypeVar("_MinMaxCompatibleNum", u16, u32, u64, i16, i32, i64, f32, f64)
"""
LLVM spits out a codegen error and then core dumps for operations on u8/i8, so
we can ban these in the type signature
"""

# max
@overload  # scalar
def max(*args: _MinMaxCompatibleNum) -> _MinMaxCompatibleNum: ...
@overload  # vector
def max(*args: qdt.Vec[_MinMaxCompatibleNum, _Dim] | _MinMaxCompatibleNum) -> qdt.Vec[_MinMaxCompatibleNum, _Dim]: ...
@overload  # matrix
def max(*args: qdt.Mat[_MinMaxCompatibleNum, _Row, _Col] | _MinMaxCompatibleNum) -> qdt.Mat[_MinMaxCompatibleNum, _Row, _Col]: ...

# min
@overload  # scalar
def min(*args: _MinMaxCompatibleNum) -> _MinMaxCompatibleNum: ...
@overload  # vector
def min(*args: qdt.Vec[_MinMaxCompatibleNum, _Dim] | _MinMaxCompatibleNum) -> qdt.Vec[_MinMaxCompatibleNum, _Dim]: ...
@overload  # matrix
def min(*args: qdt.Mat[_MinMaxCompatibleNum, _Row, _Col] | _MinMaxCompatibleNum) -> qdt.Mat[_MinMaxCompatibleNum, _Row, _Col]: ...

# predicates / integer ops (return int elements, so container type is not preserved)

# isinf
@overload  # scalar
def isinf(x: _Num) -> int: ...
@overload  # vector
def isinf(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[int, _Dim]: ...
@overload  # matrix
def isinf(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[int, _Row, _Col]: ...

# isnan
@overload  # scalar
def isnan(x: _Num) -> int: ...
@overload  # vector
def isnan(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[int, _Dim]: ...
@overload  # matrix
def isnan(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[int, _Row, _Col]: ...

# popcnt
@overload  # scalar
def popcnt(x: _Num) -> int: ...
@overload  # vector
def popcnt(x: qdt.Vec[_Num, _Dim]) -> qdt.Vec[int, _Dim]: ...
@overload  # matrix
def popcnt(x: qdt.Mat[_Num, _Row, _Col]) -> qdt.Mat[int, _Row, _Col]: ...

# clz
def clz(x: _Num) -> int: ...

# ffs
def ffs(x: _Num) -> int: ...

# fns
def fns(mask: qdt.uint, base: qdt.uint, offset: int) -> qdt.uint: ...

# vector operations
#
# `dot`/`length`/`distance`/`cross` (vec2) return the element type; `normalize`/
# `reflect`/`cross` (vec3) return the input vector unchanged.

def dot(x: qdt.Vec[_Num, _Dim], y: qdt.Vec[_Num, _Dim]) -> _Num: ...
@overload  # vec2
def cross(x: qdt.Vec[_Num, qdt.Dim2], y: qdt.Vec[_Num, qdt.Dim2]) -> _Num: ...
@overload  # vec3
def cross(x: qdt.Vec[_Num, qdt.Dim3], y: qdt.Vec[_Num, qdt.Dim3]) -> qdt.Vec[_Num, qdt.Dim3]: ...
def normalize(v: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
def reflect(x: qdt.Vec[_Num, _Dim], n: qdt.Vec[_Num, _Dim]) -> qdt.Vec[_Num, _Dim]: ...
def length(x: qdt.Vec[_Num, _Dim]) -> _Num: ...
def distance(x: qdt.Vec[_Num, _Dim], y: qdt.Vec[_Num, _Dim]) -> _Num: ...
def refract(x: qdt.Vec[_Num, _Dim], n: qdt.Vec[_Num, _Dim], eta: _Num) -> qdt.Vec[_Num, _Dim]: ...

# matrix operations
#
# `determinant` returns the element type and `inverse` keeps its square
# `Mat[_Num, _Dim, _Dim]` shape.

def determinant(m: qdt.Mat[_Num, _Dim, _Dim]) -> _Num: ...
def inverse(mat: qdt.Mat[_Num, _Dim, _Dim]) -> qdt.Mat[_Num, _Dim, _Dim]: ...
def eye(n: int) -> qdt.Mat[f32, qdt.DimAny, qdt.DimAny]: ...

# complex vec2 operations
#
# These preserve the vec2 they are given (pinned to `qdt.Dim2`). `cpow` takes a
# scalar exponent of the element type.

def cconj(z: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def cdiv(z1: qdt.Vec[_Num, qdt.Dim2], z2: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def cexp(z: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def cinv(z: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def clog(z: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def cmul(z1: qdt.Vec[_Num, qdt.Dim2], z2: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def csqrt(z: qdt.Vec[_Num, qdt.Dim2]) -> qdt.Vec[_Num, qdt.Dim2]: ...
def cpow(z: qdt.Vec[_Num, qdt.Dim2], n: _Num) -> qdt.Vec[_Num, qdt.Dim2]: ...

# transforms / constructors

def vdir(ang: float) -> qdt.Vec[float, qdt.Dim2]: ...
def rotation2d(ang: float) -> qdt.Mat[float, qdt.Dim2, qdt.Dim2]: ...
def rotation3d(ang_x: float, ang_y: float, ang_z: float) -> qdt.Mat[float, qdt.Dim4, qdt.Dim4]: ...
def rot_by_axis(axis: qdt.Vec[float, qdt.Dim3], ang: float) -> qdt.Mat[float, qdt.Dim4, qdt.Dim4]: ...
def rot_yaw_pitch_roll(yaw: float, pitch: float, roll: float) -> qdt.Mat[float, qdt.Dim4, qdt.Dim4]: ...
def scale(sx: float, sy: float, sz: float) -> qdt.Mat[float, qdt.Dim4, qdt.Dim4]: ...
def translate(dx: float, dy: float, dz: float) -> qdt.Mat[float, qdt.Dim4, qdt.Dim4]: ...
