import quadrants_typing as qdt

# `i32`/`f32` collapse to the builtins `int`/`float`, which makes code much more
# readable. quadrants is configured with 32-bit default int/float here (hence the
# `_f32_i32` package name); rebuild with the other widths collapsed to retype.
i32 = int
f32 = float

# The remaining dtypes stay nominal so that same-width-only arithmetic among
# them (e.g. `f16 + f16`) is still enforced by `qdt.NumericOps[Self]`.
class f16(qdt.Floating, qdt.Number): ...
class f64(qdt.Floating, qdt.Number): ...
class i8(qdt.SignedInteger, qdt.Number): ...
class i16(qdt.SignedInteger, qdt.Number): ...
class i64(qdt.SignedInteger, qdt.Number): ...
class u1(qdt.UnsignedInteger, qdt.Number): ...
class u8(qdt.UnsignedInteger, qdt.Number): ...
class u16(qdt.UnsignedInteger, qdt.Number): ...
class u32(qdt.UnsignedInteger, qdt.Number): ...
class u64(qdt.UnsignedInteger, qdt.Number): ...
