from typing import Literal, overload

# --- rank markers ---

class DimAny:
    """Any dimension (1..8, or unknown)."""

class DimConcrete(DimAny):
    """Any concrete dimension."""

class Dim1(DimConcrete): ...
class Dim2(DimConcrete): ...
class Dim3(DimConcrete): ...
class Dim4(DimConcrete): ...
class Dim5(DimConcrete): ...
class Dim6(DimConcrete): ...
class Dim7(DimConcrete): ...
class Dim8(DimConcrete): ...

@overload
def dim(x: Literal[1]) -> Dim1: ...
@overload
def dim(x: Literal[2]) -> Dim2: ...
@overload
def dim(x: Literal[3]) -> Dim3: ...
@overload
def dim(x: Literal[4]) -> Dim4: ...
@overload
def dim(x: Literal[5]) -> Dim5: ...
@overload
def dim(x: Literal[6]) -> Dim6: ...
@overload
def dim(x: Literal[7]) -> Dim7: ...
@overload
def dim(x: Literal[8]) -> Dim8: ...
