from typing import Generic, Iterator, Self, overload

import numpy as np
import numpy.typing as npt
import quadrants as qd
from quadrants.types.primitive_types import i32, u1

from quadrants_typing._algebra import (
    DType,
    _Dim,
    _DimAlt,
    _Num,
    _NumAlt,
    _NumInit,
)
from quadrants_typing._dim import Dim2, Dim3, Dim4, DimAny

class Vec(DType, Generic[_Num, _Dim]):
    """Fixed-length numeric vector of arbitrary dimension.

    Vectors are treated as syntactic sugar for register-to-register operations,
    thus the size of vectors should be rather small.
    """

    # Any numeric value initializes any vector — the element cast is implicit —
    # so every arg takes `_NumInit`. Overloads split only on arity/dimension.
    # `self` uses method-scoped `_NumAlt`/`_DimAlt` (class-scoped vars are barred
    # from `self` annotations).
    @overload
    def __init__(self: Vec[_NumAlt, _DimAlt], fill: _NumInit, /) -> None: ...
    @overload
    def __init__(
        self: Vec[_NumAlt, _DimAlt],
        values: list[_NumInit] | tuple[_NumInit, ...],
        /,
    ) -> None: ...
    @overload
    def __init__(self: Vec[_NumAlt, Dim2], x: _NumInit, y: _NumInit) -> None: ...
    @overload
    def __init__(self: Vec[_NumAlt, Dim3], x: _NumInit, y: _NumInit, z: _NumInit) -> None: ...
    @overload
    def __init__(
        self: Vec[_NumAlt, Dim4], x: _NumInit, y: _NumInit, z: _NumInit, w: _NumInit
    ) -> None: ...
    @property
    def x[D_: (Dim2, Dim3, Dim4)](self: Vec[_Num, D_]) -> _Num: ...
    @property
    def y[D_: (Dim2, Dim3, Dim4)](self: Vec[_Num, D_]) -> _Num: ...
    @property
    def z[D_: (Dim3, Dim4)](self: Vec[_Num, D_]) -> _Num: ...
    @property
    def w(self: Vec[_Num, Dim4]) -> _Num: ...
    def __getitem__(self, _: i32, /) -> _Num: ...
    def __setitem__(self, _: i32, val: _Num, /) -> None: ...
    def __len__(self) -> i32: ...
    def __neg__(self) -> Self: ...
    def __add__(self, other: Self | _Num, /) -> Self: ...
    def __sub__(self, other: Self | _Num, /) -> Self: ...
    def __mul__(self, other: Self | _Num, /) -> Self: ...
    def __rmul__(self, other: _Num, /) -> Self: ...
    def __mod__(self, other: Self | _Num, /) -> Self: ...
    def __rmod__(self, other: _Num, /) -> Self: ...
    def __truediv__(self, other: Self | _Num, /) -> Self: ...
    def __rtruediv__(self, other: _Num, /) -> Self: ...
    def __eq__(self, other: Self, /) -> Vec[u1, _Dim]: ...  # type: ignore[override]
    def __ne__(self, other: Self, /) -> Vec[u1, _Dim]: ...  # type: ignore[override]
    def dot(self, other: Self) -> _Num: ...
    def norm(self) -> _Num: ...
    def all(self) -> bool: ...
    def cross[D_: DimAny](self: Vec[_Num, D_], other: Vec[_Num, D_]) -> Vec[_Num, D_]: ...
    def __iter__(self) -> Iterator[_Num]: ...
    # `to_numpy` maps each concrete element dtype to its numpy counterpart
    # (mirrors `NDArray.to_numpy`). `qd.i32`/`qd.f32` are the builtins `int`/
    # `float`; the ten nominal cores map by width.
    @overload
    def to_numpy(self: Vec[qd.i8, DimAny]) -> npt.NDArray[np.int8]: ...
    @overload
    def to_numpy(self: Vec[qd.i16, DimAny]) -> npt.NDArray[np.int16]: ...
    @overload
    def to_numpy(self: Vec[qd.i32, DimAny]) -> npt.NDArray[np.int32]: ...
    @overload
    def to_numpy(self: Vec[qd.i64, DimAny]) -> npt.NDArray[np.int64]: ...
    @overload
    def to_numpy(self: Vec[qd.u1, DimAny]) -> npt.NDArray[np.bool_]: ...
    @overload
    def to_numpy(self: Vec[qd.u8, DimAny]) -> npt.NDArray[np.uint8]: ...
    @overload
    def to_numpy(self: Vec[qd.u16, DimAny]) -> npt.NDArray[np.uint16]: ...
    @overload
    def to_numpy(self: Vec[qd.u32, DimAny]) -> npt.NDArray[np.uint32]: ...
    @overload
    def to_numpy(self: Vec[qd.u64, DimAny]) -> npt.NDArray[np.uint64]: ...
    @overload
    def to_numpy(self: Vec[qd.f16, DimAny]) -> npt.NDArray[np.float16]: ...
    @overload
    def to_numpy(self: Vec[qd.f32, DimAny]) -> npt.NDArray[np.float32]: ...
    @overload
    def to_numpy(self: Vec[qd.f64, DimAny]) -> npt.NDArray[np.float64]: ...
